name: Run tests on PR
"on": pull_request
jobs:
  ci:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install
        uses: npm ci

      - name: Lint
        run: npm run lint

      - name: Types
        run: npm run types

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
